### ISSUE TITLE
PostgreSQL 执行命令失败

### ISSUE THREAD

**Issue by badboycxcc** [DeEpinGh0st/MDUT-Extend-Release#14]
PostgreSQL 执行命令失败，作者原版本可以。  

推测原因可能是判断操作系统逻辑与命令执行那块，以及识别为linux，输出结果却写Windows盘符c。

![PixPin_2024-11-20_14-51-51](https://github.com/user-attachments/assets/34a01976-6fc9-4303-85d5-7430432c5661)

**Comment by DeEpinGh0st** [comment]
感谢反馈,该问题已在下个版本解决,请关注Release更新
