### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by qery7i** [DeEpinGh0st/MDUT-Extend-Release#4]
java 环境

(base) PS C:\Users\qis\Desktop\tmp\test> java --version
java 17.0.7 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

出现错误

java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at Dao.MysqlDao.<init>(MysqlDao.java:67)
	at Controller.AddAndEditController.lambda$TestConnectAction$4(AddAndEditController.java:309)
	at java.base/java.lang.Thread.run(Thread.java:833)
![屏幕截图 2024-08-16 102727](https://github.com/user-attachments/assets/b63e8260-98e6-477b-9f1e-990fe621400b)

**Comment by DeEpinGh0st** [comment]
用jre8的版本试试

**Comment by qery7i** [comment]
8 可以

**Comment by DeEpinGh0st** [comment]
建议用8
