### ISSUE TITLE
刚准备来看看提给师傅的代理弄好没

### ISSUE THREAD

**Issue by JackeyLov5** [DeEpinGh0st/MDUT-Extend-Release#6]
rt 两小时前 orz 猛！提了issues 还是提个问题 师傅这个mdut 之前乌龙后门事件 这一版有处理过吗

**Comment by DeEpinGh0st** [comment]
有相关文章嘛

**Comment by shadow1ng** [comment]
那个就是个windows exp redis.dll被杀。无所谓吧

**Comment by DeEpinGh0st** [comment]
原版的没看到有redis.dll,1.1版本的模块是我自己编译的，放心用

**Comment by JackeyLov5** [comment]
> 那个就是个windows exp redis.dll被杀。无所谓吧

我焯 大佬！！

**Comment by JackeyLov5** [comment]
> 原版的没看到有redis.dll,1.1版本的模块是我自己编译的，放心用

好嘞
